[package]
name = "md-view"
version = "0.1.0"
edition = "2021"

[dependencies]
comrak = "0.55.0"
gpui = { git = "https://github.com/zed-industries/zed", package = "gpui", tag = "v0.233.10" }
gpui_platform = { git = "https://github.com/zed-industries/zed", package = "gpui_platform", tag = "v0.233.10", features = ["wayland"] }
notify = "8.2.0"
notify-debouncer-mini = "0.7.0"
syntect = "5.3.0"
